// Central, stable, language-independent error codes. Frontend maps each
// of these to a translated string. Never change an existing code's
// string value once shipped — only add new ones.
export const ErrorCode = {
  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  ADMIN_CREATION_FORBIDDEN: 'ADMIN_CREATION_FORBIDDEN',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_NOT_ACTIVE: 'ACCOUNT_NOT_ACTIVE',
  INVALID_TOKEN_TYPE: 'INVALID_TOKEN_TYPE',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  INVALID_SESSION: 'INVALID_SESSION',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  REFRESH_TOKEN_NOT_FOUND: 'REFRESH_TOKEN_NOT_FOUND',
  REFRESH_TOKEN_REUSE_DETECTED: 'REFRESH_TOKEN_REUSE_DETECTED',
  SESSION_REFRESH_CONFLICT: 'SESSION_REFRESH_CONFLICT',

  // Generic / infra
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  INVALID_REFERENCE: 'INVALID_REFERENCE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Vouchers
  INCOME_VOUCHER_NOT_FOUND: 'INCOME_VOUCHER_NOT_FOUND',
  EXPENSE_VOUCHER_NOT_FOUND: 'EXPENSE_VOUCHER_NOT_FOUND',
  VOUCHER_DATE_IN_FUTURE: 'VOUCHER_DATE_IN_FUTURE',
  VOUCHER_ALREADY_PROCESSED: 'VOUCHER_ALREADY_PROCESSED',
  VOUCHER_LOCKED: 'VOUCHER_LOCKED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];